# Generated by Django 3.2.4 on 2023-02-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_subscribed_users_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_packs',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subscription_packs',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='subscription_packs',
            name='period',
            field=models.PositiveIntegerField(),
        ),
    ]
