# Generated by Django 3.2.4 on 2023-02-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20230215_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_packs',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
