# Generated by Django 3.2.4 on 2023-02-15 18:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_subscription_packs_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription_packs',
            name='created_at',
        ),
        migrations.AddField(
            model_name='subscribed_users',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
